version: 1
disable_existing_loggers: False
formatters:
    simple:
      format: '%(asctime)s %(levelname)s [%(process)d:%(processName)s] %(pathname)s %(module)s %(filename)s %(funcName)s %(lineno)d %(message)s'
handlers:
    file:
      class: logging.handlers.WatchedFileHandler
      level: DEBUG
      formatter: simple
      encoding: utf-8
      filename: /var/log/pro/pro.log
root:
    level: DEBUG
    handlers: [file]
